/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RunableClasses;

import java.text.Normalizer;
import java.util.regex.Pattern;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author moises
 */
public class Registro {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) throws ParseException {

        // TODO code application logic here
        JSONArray array = regs();
        for (int i = 0; i < array.size(); i++) {
            //System.out.println(array.get(i));
            JSONObject json = (JSONObject) array.get(i);
            //System.out.println(json.get("NOMBRE "));
            String nombre = json.get("NOMBRE ").toString();
            //System.out.println(nombre.split(" ")[0]);
            String usuario = nombre.split(" ")[0] + "." + json.get("APELLIDO PATERNO");
            usuario = CleanSpecialCharts(usuario.toLowerCase());
            String apellidos = json.get("APELLIDO PATERNO") + " " + json.get("APELLIDO MATERNO");

            String correo = json.get("CORREO ELECTRONICO").toString();
            if (correo.equals("no tiene")) {
                correo = CleanSpecialCharts((nombre.split(" ")[0] + "." + json.get("APELLIDO PATERNO") + "." + json.get("APELLIDO MATERNO") + "@noteniacorreo.com").toLowerCase());
            }
            //System.out.println(correo);
            String contraseña = CleanSpecialCharts(nombre.split(" ")[0].toLowerCase()) + "12345";

//            System.out.println(usuario);
//            System.out.println(nombre);
//            System.out.println(apellidos);
//            System.out.println(correo);
//            System.out.println(contraseña);
//            System.out.println("");
              String query = "INSERT INTO `usuario_sys` (`usuario`, `nombre`, `apellidos`, `correo`, `contrasenia`, `tipo`, `estatus`, `sesion`, `disponibilidad`, `registrado_por_usuario`, `puede_registrar`) VALUES ('"+usuario+"', '"+nombre+"', '"+apellidos+"', '"+correo+"', '"+contraseña+"', 'Administrador', '1', '0', '1', '1', 'false');";
              System.out.println(query);
              System.out.println();
        }

    }

    public static String CleanSpecialCharts(String input) {
        // Descomposición canónica
        String normalized = Normalizer.normalize(input, Normalizer.Form.NFD);
        // Nos quedamos únicamente con los caracteres ASCII
        Pattern pattern = Pattern.compile("\\P{ASCII}+");
        return pattern.matcher(normalized).replaceAll("");
    }//remove2

    public static JSONArray regs() throws ParseException {
        JSONParser parser = new JSONParser();
        JSONArray array = (JSONArray) parser.parse("[\n"
                + "        {\n"
                + "            \"GRADO\": \"Mayor \",\n"
                + "            \"NOMBRE \": \"Adolfo\",\n"
                + "            \"APELLIDO PATERNO\": \"Robles\",\n"
                + "            \"APELLIDO MATERNO\": \"Murillo\",\n"
                + "            \"CORREO ELECTRONICO\": \"adolforobles335@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Mayor\",\n"
                + "            \"NOMBRE \": \"Héctor\",\n"
                + "            \"APELLIDO PATERNO\": \"Castillo\",\n"
                + "            \"APELLIDO MATERNO\": \"Moreno\",\n"
                + "            \"CORREO ELECTRONICO\": \"hcastelm@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Teniente\",\n"
                + "            \"NOMBRE \": \"Gerardo\",\n"
                + "            \"APELLIDO PATERNO\": \"Sandoval \",\n"
                + "            \"APELLIDO MATERNO\": \"Tovar\",\n"
                + "            \"CORREO ELECTRONICO\": \"gerardosantovar69@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Teniene\",\n"
                + "            \"NOMBRE \": \"Juan \",\n"
                + "            \"APELLIDO PATERNO\": \"Guevara\",\n"
                + "            \"APELLIDO MATERNO\": \"González\",\n"
                + "            \"CORREO ELECTRONICO\": \"guevarajuan123@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Damián \",\n"
                + "            \"APELLIDO PATERNO\": \"Junco \",\n"
                + "            \"APELLIDO MATERNO\": \"De La Cruz\",\n"
                + "            \"CORREO ELECTRONICO\": \"djunco458@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Teniente\",\n"
                + "            \"NOMBRE \": \"Miguel Ángel \",\n"
                + "            \"APELLIDO PATERNO\": \"Soto\",\n"
                + "            \"APELLIDO MATERNO\": \"Nava\",\n"
                + "            \"CORREO ELECTRONICO\": \"ms3006429@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Andrés \",\n"
                + "            \"APELLIDO PATERNO\": \"Pérez\",\n"
                + "            \"APELLIDO MATERNO\": \"Trujillo\",\n"
                + "            \"CORREO ELECTRONICO\": \"andres4650507@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Mayor\",\n"
                + "            \"NOMBRE \": \"Manuel \",\n"
                + "            \"APELLIDO PATERNO\": \"Bautista\",\n"
                + "            \"APELLIDO MATERNO\": \"Gaspar\"\n"
                + "\"CORREO ELECTRONICO\": \"no tiene\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capitan\",\n"
                + "            \"NOMBRE \": \"Gerardo Ismael\",\n"
                + "            \"APELLIDO PATERNO\": \"González\",\n"
                + "            \"APELLIDO MATERNO\": \"Padilla\",\n"
                + "            \"CORREO ELECTRONICO\": \"gigp180870@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Teniente\",\n"
                + "            \"NOMBRE \": \"Manuel \",\n"
                + "            \"APELLIDO PATERNO\": \"Mera\",\n"
                + "            \"APELLIDO MATERNO\": \"Escamilla\",\n"
                + "            \"CORREO ELECTRONICO\": \"manuelmeraescamilla@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Eduardo\",\n"
                + "            \"APELLIDO PATERNO\": \"Morales\",\n"
                + "            \"APELLIDO MATERNO\": \"Nequiz\",\n"
                + "            \"CORREO ELECTRONICO\": \"ikkitz.pagg@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Miguel Ángel \",\n"
                + "            \"APELLIDO PATERNO\": \"Vela \",\n"
                + "            \"APELLIDO MATERNO\": \"Díaz\",\n"
                + "            \"CORREO ELECTRONICO\": \"carri14032111@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"José Concepción \",\n"
                + "            \"APELLIDO PATERNO\": \"Bermúdez\",\n"
                + "            \"APELLIDO MATERNO\": \"Morales\",\n"
                + "            \"CORREO ELECTRONICO\": \"josebermor05@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Norberto\",\n"
                + "            \"APELLIDO PATERNO\": \"Lopez\",\n"
                + "            \"APELLIDO MATERNO\": \"Gonzalez\",\n"
                + "            \"CORREO ELECTRONICO\": \"masca13b@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Cesareo\",\n"
                + "            \"APELLIDO PATERNO\": \"Francisco \",\n"
                + "            \"APELLIDO MATERNO\": \"Jose\",\n"
                + "            \"CORREO ELECTRONICO\": \"cesarco.fco.2019@gamil.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capitan\",\n"
                + "            \"NOMBRE \": \"Juan Manuel Mariano\",\n"
                + "            \"APELLIDO PATERNO\": \"Hernadez\",\n"
                + "            \"APELLIDO MATERNO\": \"Pascual\",\n"
                + "            \"CORREO ELECTRONICO\": \"juamconstructor64@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"Jorge Esteban \",\n"
                + "            \"APELLIDO PATERNO\": \"Aguilar\",\n"
                + "            \"APELLIDO MATERNO\": \"Campohermoso\",\n"
                + "            \"CORREO ELECTRONICO\": \"campohermoso412@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"José Antonio \",\n"
                + "            \"APELLIDO PATERNO\": \"Pineda\",\n"
                + "            \"APELLIDO MATERNO\": \"Pineda\",\n"
                + "            \"CORREO ELECTRONICO\": \"josed3593070@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"Miguel Ángel \",\n"
                + "            \"APELLIDO PATERNO\": \"Azcue\",\n"
                + "            \"APELLIDO MATERNO\": \"Balmes\",\n"
                + "            \"CORREO ELECTRONICO\": \"azcbalm92@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Erik Alberto \",\n"
                + "            \"APELLIDO PATERNO\": \"Sánchez \",\n"
                + "            \"APELLIDO MATERNO\": \"Flores\",\n"
                + "            \"CORREO ELECTRONICO\": \"sanchezfloresenikalberto@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"José Juan \",\n"
                + "            \"APELLIDO PATERNO\": \"Guzmán\",\n"
                + "            \"APELLIDO MATERNO\": \"Álvarez\",\n"
                + "            \"CORREO ELECTRONICO\": \"josejuan.ricojro@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Max Alfredo\",\n"
                + "            \"APELLIDO PATERNO\": \"Meza\",\n"
                + "            \"APELLIDO MATERNO\": \"Martinez\",\n"
                + "            \"CORREO ELECTRONICO\": \"mezamartinez699@gamil.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Mayor\",\n"
                + "            \"NOMBRE \": \"Jorge Luis \",\n"
                + "            \"APELLIDO PATERNO\": \"Suárez\",\n"
                + "            \"APELLIDO MATERNO\": \"Hernandez\",\n"
                + "            \"CORREO ELECTRONICO\": \"jl.suarez.hdz@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Luciano \",\n"
                + "            \"APELLIDO PATERNO\": \"Ascencio\",\n"
                + "            \"APELLIDO MATERNO\": \"Rodriguez\",\n"
                + "            \"CORREO ELECTRONICO\": \"ascenluciano@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Adrián \",\n"
                + "            \"APELLIDO PATERNO\": \"Hernadez\",\n"
                + "            \"APELLIDO MATERNO\": \"Novas\",\n"
                + "            \"CORREO ELECTRONICO\": \"novasforever2019@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"José Elvis \",\n"
                + "            \"APELLIDO PATERNO\": \"Ruíz\",\n"
                + "            \"APELLIDO MATERNO\": \"Villanueva\",\n"
                + "            \"CORREO ELECTRONICO\": \"elguazon1978@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capitan\",\n"
                + "            \"NOMBRE \": \"Víctor \",\n"
                + "            \"APELLIDO PATERNO\": \"Lopéz\",\n"
                + "            \"APELLIDO MATERNO\": \"Lorenzo\",\n"
                + "            \"CORREO ELECTRONICO\": \"lopezlorenzo@mail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Teniente\",\n"
                + "            \"NOMBRE \": \"Abelardo Vicente \",\n"
                + "            \"APELLIDO PATERNO\": \"Reyes\",\n"
                + "            \"APELLIDO MATERNO\": \"Martínez\",\n"
                + "            \"CORREO ELECTRONICO\": \"vicentereyesmartinz575@gail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"Víctor \",\n"
                + "            \"APELLIDO PATERNO\": \"Lopéz\",\n"
                + "            \"APELLIDO MATERNO\": \"Cruz\",\n"
                + "            \"CORREO ELECTRONICO\": \"victransformers@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"Sadam \",\n"
                + "            \"APELLIDO PATERNO\": \"Ordoñez\",\n"
                + "            \"APELLIDO MATERNO\": \"Ruíz\",\n"
                + "            \"CORREO ELECTRONICO\": \"marsaorpa@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Ervin \",\n"
                + "            \"APELLIDO PATERNO\": \"Castillejos\",\n"
                + "            \"APELLIDO MATERNO\": \"López\",\n"
                + "            \"CORREO ELECTRONICO\": \"ervincastillejos84@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Adrián \",\n"
                + "            \"APELLIDO PATERNO\": \"Vázquez\",\n"
                + "            \"APELLIDO MATERNO\": \"Rosales\",\n"
                + "            \"CORREO ELECTRONICO\": \"av430899@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Gisel \",\n"
                + "            \"APELLIDO PATERNO\": \"Santos\",\n"
                + "            \"APELLIDO MATERNO\": \"Rodriguez\",\n"
                + "            \"CORREO ELECTRONICO\": \"giselsantosrodriguez908@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capitan\",\n"
                + "            \"NOMBRE \": \"Gilberto\",\n"
                + "            \"APELLIDO PATERNO\": \"Cortés\",\n"
                + "            \"APELLIDO MATERNO\": \"Sánchez\",\n"
                + "            \"CORREO ELECTRONICO\": \"artgilerias@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Teniente\",\n"
                + "            \"NOMBRE \": \"Gilberto \",\n"
                + "            \"APELLIDO PATERNO\": \"Toledo \",\n"
                + "            \"APELLIDO MATERNO\": \"Bernal\",\n"
                + "            \"CORREO ELECTRONICO\": \"gilberttoledo30@mail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Elvis Samuel \",\n"
                + "            \"APELLIDO PATERNO\": \"Suárez\",\n"
                + "            \"APELLIDO MATERNO\": \"Ruiz\",\n"
                + "            \"CORREO ELECTRONICO\": \"negroartillero@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Andrés \",\n"
                + "            \"APELLIDO PATERNO\": \"Garcia\",\n"
                + "            \"APELLIDO MATERNO\": \"Carrasco\",\n"
                + "            \"CORREO ELECTRONICO\": \"garca1408@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo\",\n"
                + "            \"NOMBRE \": \"Leonel \",\n"
                + "            \"APELLIDO PATERNO\": \"Ramirez\",\n"
                + "            \"APELLIDO MATERNO\": \"Palma\",\n"
                + "            \"CORREO ELECTRONICO\": \"leonelramirezpalma@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Mayor\",\n"
                + "            \"NOMBRE \": \"Jesús Eduardo\",\n"
                + "            \"APELLIDO PATERNO\": \"Alemán\",\n"
                + "            \"APELLIDO MATERNO\": \"Mora\",\n"
                + "            \"CORREO ELECTRONICO\": \"85esgaleman@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Teniente\",\n"
                + "            \"NOMBRE \": \"Isidro\",\n"
                + "            \"APELLIDO PATERNO\": \"Morales\",\n"
                + "            \"APELLIDO MATERNO\": \"Victorino\",\n"
                + "            \"CORREO ELECTRONICO\": \"chautengosietemil@gamil.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Edgar\",\n"
                + "            \"APELLIDO PATERNO\": \"Vivieros\",\n"
                + "            \"APELLIDO MATERNO\": \"Martínez\",\n"
                + "            \"CORREO ELECTRONICO\": \"viverosmartinez70@mail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Martín\",\n"
                + "            \"APELLIDO PATERNO\": \"García \",\n"
                + "            \"APELLIDO MATERNO\": \"Ruiz\",\n"
                + "            \"CORREO ELECTRONICO\": \"anallero0404@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Conrado\",\n"
                + "            \"APELLIDO PATERNO\": \"Santizo\",\n"
                + "            \"APELLIDO MATERNO\": \"López\",\n"
                + "            \"CORREO ELECTRONICO\": \"santizo19845@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Eric Alejandro\",\n"
                + "            \"APELLIDO PATERNO\": \"Sánchez\",\n"
                + "            \"APELLIDO MATERNO\": \"Sandoval\",\n"
                + "            \"CORREO ELECTRONICO\": \"sincler2211@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Soldado\",\n"
                + "            \"NOMBRE \": \"Yazmin Yaneth\",\n"
                + "            \"APELLIDO PATERNO\": \"Orellana\",\n"
                + "            \"APELLIDO MATERNO\": \"López\",\n"
                + "            \"CORREO ELECTRONICO\": \"333mart@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Mayor\",\n"
                + "            \"NOMBRE \": \"Baltazar\",\n"
                + "            \"APELLIDO PATERNO\": \"Mancilla\",\n"
                + "            \"APELLIDO MATERNO\": \"Manriquez\",\n"
                + "            \"CORREO ELECTRONICO\": \"bmmmex9902@gamil.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capitan\",\n"
                + "            \"NOMBRE \": \"Baldomero\",\n"
                + "            \"APELLIDO PATERNO\": \"Morales\",\n"
                + "            \"APELLIDO MATERNO\": \"Cruz\",\n"
                + "            \"CORREO ELECTRONICO\": \"morelezcruzbaldomero@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"Jorge Andrei\",\n"
                + "            \"APELLIDO PATERNO\": \"Lozano\",\n"
                + "            \"APELLIDO MATERNO\": \"Del Ángel\",\n"
                + "            \"CORREO ELECTRONICO\": \"war.gio.gio@gamil.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Angel\",\n"
                + "            \"APELLIDO PATERNO\": \"Juarez\",\n"
                + "            \"APELLIDO MATERNO\": \"Perez\",\n"
                + "            \"CORREO ELECTRONICO\": \"angelit.itoito@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Melesio\",\n"
                + "            \"APELLIDO PATERNO\": \"Guzmán\",\n"
                + "            \"APELLIDO MATERNO\": \"San Juan\",\n"
                + "            \"CORREO ELECTRONICO\": \"mg25j03@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Ezequiel\",\n"
                + "            \"APELLIDO PATERNO\": \"Roque\",\n"
                + "            \"APELLIDO MATERNO\": \"Ramirez\",\n"
                + "            \"CORREO ELECTRONICO\": \"sol84cazador@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Gilberto\",\n"
                + "            \"APELLIDO PATERNO\": \"Gamboa\",\n"
                + "            \"APELLIDO MATERNO\": \"Perez\",\n"
                + "            \"CORREO ELECTRONICO\": \"gilbertogamboaperez@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Mayor\",\n"
                + "            \"NOMBRE \": \"Arturo\",\n"
                + "            \"APELLIDO PATERNO\": \"Martínez \",\n"
                + "            \"APELLIDO MATERNO\": \"Martínez\",\n"
                + "            \"CORREO ELECTRONICO\": \"cazador4473@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capitan\",\n"
                + "            \"NOMBRE \": \"Horacio\",\n"
                + "            \"APELLIDO PATERNO\": \"González\",\n"
                + "            \"APELLIDO MATERNO\": \"Leucona\",\n"
                + "            \"CORREO ELECTRONICO\": \"ranger09555@gail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Teniente\",\n"
                + "            \"NOMBRE \": \"Luis Alberto\",\n"
                + "            \"APELLIDO PATERNO\": \"Hernández\",\n"
                + "            \"APELLIDO MATERNO\": \"Juárez\",\n"
                + "            \"CORREO ELECTRONICO\": \"spartaco1587@gamil.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Pedro\",\n"
                + "            \"APELLIDO PATERNO\": \"López\",\n"
                + "            \"APELLIDO MATERNO\": \"Pérez\",\n"
                + "            \"CORREO ELECTRONICO\": \"piter1845@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Luciano\",\n"
                + "            \"APELLIDO PATERNO\": \"López\",\n"
                + "            \"APELLIDO MATERNO\": \"Fabián\",\n"
                + "            \"CORREO ELECTRONICO\": \"favian45577@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Adrián\",\n"
                + "            \"APELLIDO PATERNO\": \"Méndez\",\n"
                + "            \"APELLIDO MATERNO\": \"Cruz\",\n"
                + "            \"CORREO ELECTRONICO\": \"adrian155448@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Daniel\",\n"
                + "            \"APELLIDO PATERNO\": \"Zavala\",\n"
                + "            \"APELLIDO MATERNO\": \"Solís\",\n"
                + "            \"CORREO ELECTRONICO\": \"dz190490@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Mayor\",\n"
                + "            \"NOMBRE \": \"Surisaday \",\n"
                + "            \"APELLIDO PATERNO\": \"Hernández\",\n"
                + "            \"APELLIDO MATERNO\": \"González\",\n"
                + "            \"CORREO ELECTRONICO\": \"chilnagoizta87@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capitan\",\n"
                + "            \"NOMBRE \": \"Fernando\",\n"
                + "            \"APELLIDO PATERNO\": \"Rosales\",\n"
                + "            \"APELLIDO MATERNO\": \"Pinales\",\n"
                + "            \"CORREO ELECTRONICO\": \"ferropi@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"José Francisco\",\n"
                + "            \"APELLIDO PATERNO\": \"Rosas\",\n"
                + "            \"APELLIDO MATERNO\": \"López\",\n"
                + "            \"CORREO ELECTRONICO\": \"frank930929em@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Francisco\",\n"
                + "            \"APELLIDO PATERNO\": \"Ochoa\",\n"
                + "            \"APELLIDO MATERNO\": \"Méndez\",\n"
                + "            \"CORREO ELECTRONICO\": \"fo092174@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Gabriel\",\n"
                + "            \"APELLIDO PATERNO\": \"Solano\",\n"
                + "            \"APELLIDO MATERNO\": \"Segura\",\n"
                + "            \"CORREO ELECTRONICO\": \"solanosegura6@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Rogelio\",\n"
                + "            \"APELLIDO PATERNO\": \"Santos\",\n"
                + "            \"APELLIDO MATERNO\": \"Serafín\",\n"
                + "            \"CORREO ELECTRONICO\": \"serafinrogelio@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Maximo\",\n"
                + "            \"APELLIDO PATERNO\": \"May\",\n"
                + "            \"APELLIDO MATERNO\": \"Cahuich\",\n"
                + "            \"CORREO ELECTRONICO\": \"maximomaycavich@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Mayor\",\n"
                + "            \"NOMBRE \": \"Enrique \",\n"
                + "            \"APELLIDO PATERNO\": \"Amador\",\n"
                + "            \"APELLIDO MATERNO\": \"Cruz\",\n"
                + "            \"CORREO ELECTRONICO\": \"lanz22123574@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capitan\",\n"
                + "            \"NOMBRE \": \"Rafael \",\n"
                + "            \"APELLIDO PATERNO\": \"Juarez\",\n"
                + "            \"APELLIDO MATERNO\": \"Gonzalez\",\n"
                + "            \"CORREO ELECTRONICO\": \"pantrokimura@mail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"José Antonio \",\n"
                + "            \"APELLIDO PATERNO\": \"Castillo\",\n"
                + "            \"APELLIDO MATERNO\": \"Rosas\",\n"
                + "            \"CORREO ELECTRONICO\": \"joseantoniocastillo210@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Mario\",\n"
                + "            \"APELLIDO PATERNO\": \"Lopez\",\n"
                + "            \"APELLIDO MATERNO\": \"Mora\",\n"
                + "            \"CORREO ELECTRONICO\": \"mariolopezmora058@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"José Francisco \",\n"
                + "            \"APELLIDO PATERNO\": \"Aguilar\",\n"
                + "            \"APELLIDO MATERNO\": \"París\",\n"
                + "            \"CORREO ELECTRONICO\": \"pentagono31x@gail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Juan \",\n"
                + "            \"APELLIDO PATERNO\": \" De Jesús\",\n"
                + "            \"APELLIDO MATERNO\": \"Paz\",\n"
                + "            \"CORREO ELECTRONICO\": \"jjap2792@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Lázaro\",\n"
                + "            \"APELLIDO PATERNO\": \"Mateo\",\n"
                + "            \"APELLIDO MATERNO\": \"Jiménez\",\n"
                + "            \"CORREO ELECTRONICO\": \"mateolazaro@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Mayor\",\n"
                + "            \"NOMBRE \": \"Marco Antonio \",\n"
                + "            \"APELLIDO PATERNO\": \"Herlindo\",\n"
                + "            \"APELLIDO MATERNO\": \"Inocencio\",\n"
                + "            \"CORREO ELECTRONICO\": \"papismarco5986@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Teniente\",\n"
                + "            \"NOMBRE \": \"Carlos Alberto \",\n"
                + "            \"APELLIDO PATERNO\": \"Medina\",\n"
                + "            \"APELLIDO MATERNO\": \"Hernández\",\n"
                + "            \"CORREO ELECTRONICO\": \"bluecanito@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Omar Islas \",\n"
                + "            \"APELLIDO PATERNO\": \"Islas\",\n"
                + "            \"APELLIDO MATERNO\": \"Hernández\",\n"
                + "            \"CORREO ELECTRONICO\": \"omarin265871@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Miguel Roberto \",\n"
                + "            \"APELLIDO PATERNO\": \"Medina\",\n"
                + "            \"APELLIDO MATERNO\": \"Rodríguez\",\n"
                + "            \"CORREO ELECTRONICO\": \"miguelmedinarodriguez@mail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Luis Alberto  \",\n"
                + "            \"APELLIDO PATERNO\": \"Mijangos\",\n"
                + "            \"APELLIDO MATERNO\": \"Hernández\",\n"
                + "            \"CORREO ELECTRONICO\": \"galaxiuz987654@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"Jorge Uriel \",\n"
                + "            \"APELLIDO PATERNO\": \"Cortes\",\n"
                + "            \"APELLIDO MATERNO\": \"Morales\",\n"
                + "            \"CORREO ELECTRONICO\": \"uriel.cortestransmisiones@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Orlando \",\n"
                + "            \"APELLIDO PATERNO\": \"De Los Santos \",\n"
                + "            \"APELLIDO MATERNO\": \"Oliva\",\n"
                + "            \"CORREO ELECTRONICO\": \"delosantoso074@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Anastacio \",\n"
                + "            \"APELLIDO PATERNO\": \"Regalado\",\n"
                + "            \"APELLIDO MATERNO\": \"Silva\",\n"
                + "            \"CORREO ELECTRONICO\": \"regaladosilvainf.@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Alejandro \",\n"
                + "            \"APELLIDO PATERNO\": \"Hernández\",\n"
                + "            \"APELLIDO MATERNO\": \"Solis\",\n"
                + "            \"CORREO ELECTRONICO\": \"alejandro.solisa@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Mayor\",\n"
                + "            \"NOMBRE \": \"Luis Ángel \",\n"
                + "            \"APELLIDO PATERNO\": \"Santos\",\n"
                + "            \"APELLIDO MATERNO\": \"Iza\",\n"
                + "            \"CORREO ELECTRONICO\": \"max.1978.lasi@mail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capitan\",\n"
                + "            \"NOMBRE \": \"Christian Yahir \",\n"
                + "            \"APELLIDO PATERNO\": \"Noguera\",\n"
                + "            \"APELLIDO MATERNO\": \"Díaz\",\n"
                + "            \"CORREO ELECTRONICO\": \"tecuan851128@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"Félix \",\n"
                + "            \"APELLIDO PATERNO\": \"Espinosa\",\n"
                + "            \"APELLIDO MATERNO\": \"Cayetano\",\n"
                + "            \"CORREO ELECTRONICO\": \"cayesespinosa@gamil.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Román \",\n"
                + "            \"APELLIDO PATERNO\": \"Francisico\",\n"
                + "            \"APELLIDO MATERNO\": \"Peralta\",\n"
                + "            \"CORREO ELECTRONICO\": \"francisco198236@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Felipe \",\n"
                + "            \"APELLIDO PATERNO\": \"Juárez\",\n"
                + "            \"APELLIDO MATERNO\": \"Marcos\",\n"
                + "            \"CORREO ELECTRONICO\": \"marcos.juarez.8153@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Alejandro \",\n"
                + "            \"APELLIDO PATERNO\": \"Mosqueda\",\n"
                + "            \"APELLIDO MATERNO\": \"Moreno\",\n"
                + "            \"CORREO ELECTRONICO\": \"mosquedamayo26@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Mayor\",\n"
                + "            \"NOMBRE \": \"José Luis \",\n"
                + "            \"APELLIDO PATERNO\": \"Espinoza \",\n"
                + "            \"APELLIDO MATERNO\": \"Mercado\",\n"
                + "            \"CORREO ELECTRONICO\": \"jlem7575@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capotan\",\n"
                + "            \"NOMBRE \": \"Antonio\",\n"
                + "            \"APELLIDO PATERNO\": \"Gallegos\",\n"
                + "            \"APELLIDO MATERNO\": \"Anrubio\",\n"
                + "            \"CORREO ELECTRONICO\": \"anrubio1988@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"Sergio \",\n"
                + "            \"APELLIDO PATERNO\": \"Villerías\",\n"
                + "            \"APELLIDO MATERNO\": \"Simbrón\",\n"
                + "            \"CORREO ELECTRONICO\": \"villeriasf75@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Erick David\",\n"
                + "            \"APELLIDO PATERNO\": \"Guitiérrez\",\n"
                + "            \"APELLIDO MATERNO\": \"Vázquez\",\n"
                + "            \"CORREO ELECTRONICO\": \"alucardox12345@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"José \",\n"
                + "            \"APELLIDO PATERNO\": \"Cortez\",\n"
                + "            \"APELLIDO MATERNO\": \"Martínez\",\n"
                + "            \"CORREO ELECTRONICO\": \"jcm81921@mail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"David De Jesús\",\n"
                + "            \"APELLIDO PATERNO\": \"Ramírez\",\n"
                + "            \"APELLIDO MATERNO\": \"Pascual\",\n"
                + "            \"CORREO ELECTRONICO\": \"davidramirez22652@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capitan\",\n"
                + "            \"NOMBRE \": \"Marco Antonio \",\n"
                + "            \"APELLIDO PATERNO\": \"Cruz\",\n"
                + "            \"APELLIDO MATERNO\": \"Blancarte\",\n"
                + "            \"CORREO ELECTRONICO\": \"macb8136@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Teniente\",\n"
                + "            \"NOMBRE \": \"Pedro Alberto \",\n"
                + "            \"APELLIDO PATERNO\": \"Gonzales\",\n"
                + "            \"APELLIDO MATERNO\": \"Torres\",\n"
                + "            \"CORREO ELECTRONICO\": \"piteraltamirano832@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"Jesús \",\n"
                + "            \"APELLIDO PATERNO\": \"Onofre\",\n"
                + "            \"APELLIDO MATERNO\": \"López\",\n"
                + "            \"CORREO ELECTRONICO\": \"siempre.leales.infanteria@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Carmen \",\n"
                + "            \"APELLIDO PATERNO\": \"Mendoza\",\n"
                + "            \"APELLIDO MATERNO\": \"López\",\n"
                + "            \"CORREO ELECTRONICO\": \"mendoza@198039gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capitan\",\n"
                + "            \"NOMBRE \": \"José Octavio \",\n"
                + "            \"APELLIDO PATERNO\": \"Bocanegre\",\n"
                + "            \"APELLIDO MATERNO\": \"Trejo\",\n"
                + "            \"CORREO ELECTRONICO\": \"prisglochris1974@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Subteniente\",\n"
                + "            \"NOMBRE \": \"Iván Calderón \",\n"
                + "            \"APELLIDO PATERNO\": \"Calderón\",\n"
                + "            \"APELLIDO MATERNO\": \"Echeverría\",\n"
                + "            \"CORREO ELECTRONICO\": \"icerz9209@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Sargento\",\n"
                + "            \"NOMBRE \": \"Carlos Humberto \",\n"
                + "            \"APELLIDO PATERNO\": \"Cruz\",\n"
                + "            \"APELLIDO MATERNO\": \"Cabrera\",\n"
                + "            \"CORREO ELECTRONICO\": \"karloskruz2010@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Sebastian\",\n"
                + "            \"APELLIDO PATERNO\": \"Montejo\",\n"
                + "            \"APELLIDO MATERNO\": \"De La Rosa\",\n"
                + "            \"CORREO ELECTRONICO\": \"vildestrolle@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Yasmany Argel \",\n"
                + "            \"APELLIDO PATERNO\": \"Gonzalez\",\n"
                + "            \"APELLIDO MATERNO\": \"Canchola\",\n"
                + "            \"CORREO ELECTRONICO\": \"yasmanyargel@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Hermelindo \",\n"
                + "            \"APELLIDO PATERNO\": \"Hidalgo\",\n"
                + "            \"APELLIDO MATERNO\": \"Cerino\",\n"
                + "            \"CORREO ELECTRONICO\": \"hhidalgocerino@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Capitan\",\n"
                + "            \"NOMBRE \": \"Héctor \",\n"
                + "            \"APELLIDO PATERNO\": \"Remírez\",\n"
                + "            \"APELLIDO MATERNO\": \"Roldán\",\n"
                + "            \"CORREO ELECTRONICO\": \"no tiene\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Teniente\",\n"
                + "            \"NOMBRE \": \"Milton Noé \",\n"
                + "            \"APELLIDO PATERNO\": \"Rodriguez\",\n"
                + "            \"APELLIDO MATERNO\": \"Huamantla\",\n"
                + "            \"CORREO ELECTRONICO\": \"miltonnrh@gmail.com\"\n"
                + "        },\n"
                + "        {\n"
                + "            \"GRADO\": \"Cabo \",\n"
                + "            \"NOMBRE \": \"Miriel \",\n"
                + "            \"APELLIDO PATERNO\": \"Henschi\",\n"
                + "            \"APELLIDO MATERNO\": \"Guerra\",\n"
                + "            \"CORREO ELECTRONICO\": \"hengschiguerra@gmail.com\"\n"
                + "        }\n"
                + "    ]");

        return array;
    }

}
